language: php

addons:
  ssh_known_hosts: bitbucket.org

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS chamb_testing;'
  - php artisan migrate -n
  - npm install -g bower
  - npm install -g gulp
  - bower install -s

before_install:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer require satooshi/php-coveralls

script:
  - phpunit tests/ --coverage-clover tests/build/logs/clover.xml
  - gulp

after_script: php vendor/bin/coveralls -v
