language: php

php:
  - 5.5.9
  - 5.6
  - 7.0
  - hhvm

services:
  - mysql

before_script:
  - composer self-update
  - mysql -e 'CREATE DATABASE IF NOT EXISTS chamb_testing;'
  - php artisan migrate:refresh --seed -n

install:
  - composer install --prefer-source --no-interaction
  - npm install -g bower
  - bower install

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: hhvm

script: vendor/bin/phpunit